env: "development"

# Флаги запуска модулей по умолчанию (флаги CLI могут их переопределить)
launch_datamobile: false
launch_lmcz_check: false
launch_lmcz_init: false
client_request_timeout: "10s"   # Будет автоматически распарсено в time.Duration

datamobile:
  user: "admin"
  pass: ""

apache:
  publication_name: "tradeProfilDm"
  # tradeProfilDm / polyMark
  address: "localhost"
  # 192.168.0.75 / localhost
  port: ""
  conf_path: C:/Apache24/conf/httpd.conf
  # ssh drk@192.168.0.75 cd /etc/apache2/ apache2.conf // Путь к конфигурационному файлу Apache (для Windows или Linux)
  warning_duration: "2s"

lmcz:
  # Схемы не нужны!
  host: "localhost"
  # "localhost" "sidingkas"
  subnet: "192.168.0"
  port: "5998"
  scanner_timeout: "500ms"
  user: "admin"
  pass: "admin"
  token_x_api_key: "ce6df78c-a28c-4f6f-b636-8cc28b46315f"
  # ce6df78c-a28c-4f6f-b636-8cc28b46315f "Профиль"